# Generated by Django 5.1.1 on 2025-05-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='id_comentario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
