# Generated by Django 5.1.6 on 2025-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_publicacion_id_comentario_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='photo',
            field=models.FileField(default='img/pfp/default.jpg', upload_to='img/pfp/'),
        ),
    ]
